### ISSUE TITLE
Disable setting keymaps when they are nil

### ISSUE THREAD

**Issue by gramic** [AntonVanAssche/date-time-inserter.nvim#1]
**Is your feature request related to a problem? Please describe.**
I am using [Lazy](https://github.com/folke/lazy.nvim) for configuration that loads lazily plugins when *keys* are mapped. However, setting *insert_date_map* to nil or empty string raises error in [date-time-inserter.nvim](https://github.com/AntonVanAssche/date-time-inserter.nvim)

**Describe the solution you'd like**
Allow *insert_\*_map* keys to be nil or empty without error.

**Describe alternatives you've considered**
I tried with nil and empty strings for the mapping of *insert_date_time_map* without success.

**Additional context**
Example of my configuration:

```yaml
  {
    "AntonVanAssche/date-time-inserter.nvim",
    ft = "markdown",
    opts = {
      date_format = "DDMMYYYY",
      date_separator = ".",
      time_format = 24,
      insert_date_map = "",
      insert_time_map = "",
      insert_date_time_map = "",
    },
    keys = {
      {
        "<leader>tt",
        "<cmd>InsertDateTime<cr>",
        desc = "Insert date and time.",
      },
      {
        "<M-;>",
        "<cmd>InsertDateTime<cr>",
        mode = { "i" },
        desc = "Insert date and time.",
      },
    },
  },
```

**Comment by AntonVanAssche** [comment]
Hi @gramic,

Thank you for bringing this to my attention. I understand the issue you're facing with the `insert_*_map keys` when set to `nil` or an empty string.

To address this, I'm considering two potential solutions:

1. **Check for `nil` or Empty String:**

I can modify the code to include a check for `nil` or an empty string when handling the keymaps. This way, users can set `insert_*_map` to `nil` or an empty string without triggering an error. I believe this is what you were suggesting, is that correct?

The solution would look similar to this:

```lua
local function setting_is_empty(setting)
    return setting == nil or setting == ''
end

M.setup = function(opts)
    if opts then
        for k, v in pairs(opts) do
            settings[k] = v
        end
    end

    if not setting_is_empty(settings.insert_date_time_map) then
        set_keymap(settings.insert_date_time_map, M.insert_date_time)
    end

    if not setting_is_empty(settings.insert_time_map) then
        set_keymap(settings.insert_time_map, M.insert_time)
    end

    if not setting_is_empty(settings.insert_date_map) then
        set_keymap(settings.insert_date_map, M.insert_date)
    end
end
```

2. **Optional Keymap Configuration:**

Alternatively, I could remove the keymap assignments entirely, allowing users to choose whether they want to set a keymap or leave it unassigned. This approach provides more flexibility in customization.

I would like to hear your thoughts on these proposed solutions. If you have a preference or any other suggestions, please let me know.

Thank you for your patience and collaboration!

Warmest regards,
Anton

**Comment by gramic** [comment]
Options 1 seems to be preferable. Usually plugin developers leave key mappings alone, so the user can decide what and how to do it. However, providing some default settings and mappings is better than nothing at all.

**Comment by AntonVanAssche** [comment]
The fix has been merged into the `master` branch. I'm closing this issue now. If you encounter any further issues or have additional concerns related to this matter, please feel free to reopen this
